Web Symbols: add documentation about WebSymbolContext support.
JetBrains/intellij-sdk-docs pull request #1307
Opened 2024-05-14 08:34 UTC by piotrtomiak

2024-05-14 09:18 UTC, YannCebron requested changes

2024-05-14 09:18 UTC, YannCebron commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +Usually, the coding assistance logic is working with `PsiElement`, so you should provide it as the location
do not use "you" anywhere

2024-05-14 09:18 UTC, YannCebron commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +And each of the plugins calls `WebSymbolsContext.get("framework", ...)` method to check if it's their framework,
remove "method"

2024-05-14 09:18 UTC, YannCebron commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +through `com.intellij.webSymbols.context` and override one of `isEnabled` methods
.. context` extension point and ...

`isEnabled` -> `isEnabled()`

2024-05-14 09:18 UTC, YannCebron commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +should be present in the file. The calculations should be cached, as `WebSymbolsContextProvider` methods are called very often.
calculations -> result

2024-05-14 09:18 UTC, YannCebron commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +WebSymbols.get("stimulus-context", psiElement) == "true"
what is "WebSymbols"

2024-05-14 09:18 UTC, YannCebron commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +a lot of calculations are repeated and the performance of the whole IDE drops down. One of the examples is when providers look for the presence
a lot of calculations are repeated affecting the overall performance of the IDE.

2024-05-14 09:18 UTC, YannCebron commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +through `com.intellij.webSymbols.queryConfigurator` extension point and implement `getContextRulesProviders()` method.
remove "method".

2024-05-14 09:18 UTC, YannCebron commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +rescanning of the project, dropping of all caches and restarting code analysis deamon.
remove "deamon"

2024-05-14 09:18 UTC, YannCebron commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +`WebSymbolsContextSourceProximityProvider` allows providing evaluation logic for the context rules. This interface should be used if
It should be used when working on...

2024-05-14 09:18 UTC, YannCebron commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +The provider has a single method to be overridden — `calculateProximity`. When `sourceKind` parameter matches the provider requirements,
calculateProximity()

2024-05-14 09:18 UTC, YannCebron commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +is used to track when the cached results should be recalculated. It is crucial to as few trackers as possible and refresh the cache as little as possible
as little as -> as seldom as

2024-05-14 09:19 UTC, YannCebron commented
code-links to be added by us + "what's new"

2024-05-14 13:53 UTC, karollewandowski requested changes

2024-05-14 13:53 UTC, karollewandowski commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +The location can either be a `PsiElement` or a `VirtualFile` with a `Project`. If the location is `PsiElement`,
```suggestion
The location can either be a `PsiElement`, or a `VirtualFile` with a `Project`. If the location is `PsiElement`,
```
Not sure about it. Without comma, it sounds like both PsiElement and VirtualFile are subject of "with a Project".

2024-05-14 13:53 UTC, karollewandowski commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +```
````suggestion
```xml
<idea-plugin>
  <extensions defaultExtensionNs="com.intellij">
    <webSymbols.context 
        kind="stimulus-context" name="true"
        implementation="com.intellij.stimulus.context.StimulusContextProvider"/>
  </extensions>
</idea-plugin>
```
````
I bit narrower code snippet.

2024-05-14 13:53 UTC, karollewandowski commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +should be present in the file. The calculations should be cached, as `WebSymbolsContextProvider` methods are called very often.
It would be nice to give a caching example.

2024-05-14 13:53 UTC, karollewandowski commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +```
````suggestion
```xml
<idea-plugin>
  <extensions defaultExtensionNs="com.intellij">
    <webSymbols.context
        kind="framework" name="any"
        implementation="com.intellij.python.js.PyTemplatesWebContextBlocker"/>
  </extensions>
</idea-plugin>
```
````
A bit narrower code snippet.

2024-05-14 13:53 UTC, karollewandowski commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +To prevent any context of a particular kind, use `any` as a name. E.g.:
```suggestion
To prevent any context of a particular kind, use `any` as a name, e.g.:
```

2024-05-14 13:53 UTC, karollewandowski commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +## Context rules
```suggestion
## Context Rules
```
Title Case

2024-05-14 13:53 UTC, karollewandowski commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +### Web Types with context rules
```suggestion
### Web Types with Context Rules
```
Title Case

2024-05-14 13:53 UTC, karollewandowski commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +In IDEs prior to 2024.2 only a deprecated syntax is supported, where the first level property under `contexts-config` is the context `name`
```suggestion
In IDEs prior to 2024.2, only a deprecated syntax is supported, where the first level property under `contexts-config` is the context `name`
```

2024-05-14 13:53 UTC, karollewandowski commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +and the context kind needs to be specified through `kind` property. E.g.:
```suggestion
and the context kind needs to be specified through `kind` property, e.g.:
```

2024-05-14 13:53 UTC, karollewandowski commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +#### Context proximity
```suggestion
#### Context Proximity
```
Title Case

2024-05-14 13:53 UTC, karollewandowski commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +</idea-plugin>
```suggestion
<idea-plugin>
  <extensions defaultExtensionNs="com.intellij">
    <webSymbols.webTypes
        source="web-types/vue-store-contexts@0.0.0.web-types.json"
        enableByDefault="true"/>
  </extensions>
</idea-plugin>
```
A bit narrower code snippet.

2024-05-14 13:53 UTC, karollewandowski commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +correspond to any dependency, so we can name the file as we want to. Currently only Node Package Manager
```suggestion
correspond to any dependency, so we can name the file as we want to. Currently, only Node Package Manager
```

2024-05-14 13:53 UTC, karollewandowski commented on topics/reference_guide/custom_language_support/websymbols_context.md
> +is used to track when the cached results should be recalculated. It is crucial to as few trackers as possible and refresh the cache as little as possible
```suggestion
is used to track when the cached results should be recalculated. It is crucial to have as few trackers as possible and refresh the cache as little as possible
```

2024-05-16 07:45 UTC, piotrtomiak commented
@YannCebron @karollewandowski Thanks for the review! All the suggestions were applied. We're ready for round #2 :)

2024-05-16 08:37 UTC, YannCebron approved these changes

2024-05-16 10:14 UTC, karollewandowski approved these changes

2024-05-16 10:44 UTC, merged