Docs maintenance
JetBrains/intellij-sdk-docs pull request #316
Opened 2020-09-08 20:48 UTC by hsz

2020-09-09 08:30 UTC, YannCebron requested changes

2020-09-09 08:30 UTC, YannCebron commented on basics/plugin_structure/dynamic_plugins.md
> +Starting with the 2020.1 release, installing, updating, and uninstall plugins without restarting the IDE is available in the IntelliJ Platform.
uninstalling

2020-09-09 08:30 UTC, YannCebron commented on basics/plugin_structure/dynamic_plugins.md
> +Application, project, and module services declared with `overrides=" true" ` are not allowed.
why space?

2020-09-09 08:30 UTC, YannCebron commented on basics/plugin_structure/dynamic_plugins.md
> +> **NOTE** Loading and unloading plugins happens in EDT and underwrite action.
write action is a term

2020-09-09 08:30 UTC, YannCebron commented on basics/plugin_structure/plugin_content.md
> +The plugin `.jar` file is placed in the `/lib` folder under the plugin's "root" folder and all required bundled libraries.
IMHO confusing now

2020-09-09 08:30 UTC, YannCebron commented on products/rider.md
> +The Rider uses the IntelliJ Platform to provide the user interface for a C# and .NET IDE but uses ReSharper to provide the language-specific features.
Rider is a product name

2020-09-09 08:30 UTC, YannCebron commented on products/rider.md
> +The article is an excellent counterpoint to the ReSharper DevGuide content, which discusses the code level protocol.
meaning of sentence changed

2020-09-09 08:30 UTC, YannCebron commented on products/webstorm.md
> +**Note** that for WebStorm, the plugin.xml file must also declare a dependency on `com.intellij.modules.platformx` because `JavaScriptLanguage` is not recognized as a module.
platformx?

2020-09-09 08:30 UTC, YannCebron commented on reference_guide/api_changes/api_changes_list_2019.md
> +NOTE: Entries not starting with code quotes (`name`) can be added to document non-code changes and be skipped in API verification.
no

2020-09-09 08:30 UTC, YannCebron commented on reference_guide/api_changes/api_changes_list_2020.md
> +NOTE: Entries not starting with code quotes (`name`) can be added to document non-code changes and be skipped in API verification.
no

2020-09-09 08:30 UTC, YannCebron commented on reference_guide/api_changes/api_changes_list_2020.md
> +: Due to some problems in Kotlin compiler, existing Kotlin code might become incompatible in rare cases if a method is written in Java returning an array and annotated as `@Nullable` or `@NotNull` is
incompilable and incompatible are two distinct things

2020-09-09 08:30 UTC, YannCebron commented on reference_guide/frameworks_and_external_apis/spring_api.md
> +Please use only Spring-related functionality exposed in `spring-api.jar` (where your plugin is provided). Using any other "internal" (implementation) classes from Spring plugin itself (`spring.jar`)
wrong

2020-09-09 08:30 UTC, YannCebron commented on tutorials/action_system/grouping_action.md
> +This tutorial demonstrates adding an action to an existing group, creating a new action group, and action groups with various actions.
change of meaning

2020-09-09 08:30 UTC, YannCebron commented on basics/architectural_overview/file_view_providers.md
> +Each of the PSI trees covers the entire contents of the file and contains unique "outer language elements" in the places where contents in a different language can be found.
special != unique

2020-09-09 08:30 UTC, YannCebron commented on basics/architectural_overview/general_threading_rules.md
> +: The operation will be executed as soon as possible regardless of modal dialogs. Please note that modifying PSI, VFS, or project model is prohibited from such runnable.
IMHO plural is correct

2020-09-09 08:30 UTC, YannCebron commented on basics/architectural_overview/general_threading_rules.md
> +For visible progress, threads can use `ProgressIndicator` to notify the user about current status:
plural?

2020-09-09 08:30 UTC, YannCebron commented on basics/getting_started/plugin_compatibility.md
> +For example, PhpStorm does not have its own module, but its product depends on (and ships with) the PHP language plugin.
PhpStorm _is_ the product

2020-09-09 08:30 UTC, YannCebron commented on basics/persisting_state_of_components.md
> +The *IntelliJ Platform* provides an API that allows components or services to persist their state between the IDE restarts. You can use either a simple API to persist a few values or persist the stat
"between the IDE restarts." grammar?

2020-09-09 08:30 UTC, YannCebron commented on basics/persisting_state_of_components.md
> +Note that instances of extensions cannot persist in their state by implementing `PersistentStateComponent`. If your extension needs to have a persistent state, you need to define a separate service r
no

2020-09-09 08:30 UTC, YannCebron commented on basics/persisting_state_of_components.md
> +* `storages` — one or more of `@com.intellij.openapi.components.Storage` annotations to determine the storage locations. Optional for project-level values — standard project file is used in this case
specify != determine

2020-09-09 08:30 UTC, YannCebron commented on basics/persisting_state_of_components.md
> +The `loadState()` method is called after the component has been created (only if some non-default state persisted for the component). After the XML file with the persisted state is changed externally
grammar?

2020-09-10 04:18 UTC, JohnHake reviewed
Rather than enumerate additional points, I'll leave more general feedback on #advocates-ij-platform.

2020-09-10 04:18 UTC, JohnHake commented on CONTRIBUTING.md
> +It can be switched to a different branch using `git checkout`, and any changes to the currently checked out revision need to be committed back into the main repository using git commands.
Superfluous change.

2020-09-10 04:18 UTC, JohnHake commented on CONTRIBUTING.md
> +If changes are made to the submodule, they should be made on a branch to a clone, and a Pull Request sent.
Superfluous change.

2020-09-10 04:18 UTC, JohnHake commented on CONTRIBUTING.md
> +* [SDK Documentation Style Guide](intro/sdk_style.md).
Superfluous change.

2020-09-10 04:18 UTC, JohnHake commented on CONTRIBUTING.md
> +* [SDK Code Sample Guidelines](intro/sdk_code_guidelines.md).
Superfluous change.

2020-09-10 04:18 UTC, JohnHake commented on CONTRIBUTING.md
> -
Superfluous change.

2020-09-10 04:18 UTC, JohnHake commented on CONTRIBUTING.md
> +The Docker image is also used to build the [published site](https://www.jetbrains.org/intellij/sdk/docs/index.html), so it is a known working environment.
Correct changes (here and elsewhere in this doc) per our style guide, but these aren't content changes. Is it wiser to postpone style cleanup until the technical content is correct? (IJSDK-252, IJSDK-575)

2020-09-10 04:18 UTC, JohnHake commented on README.md
> +The code samples can also be found in [IntelliJ SDK Code Samples](https://github.com/JetBrains/intellij-sdk-code-samples) mirror repository.
Superfluous style change

2020-09-10 04:18 UTC, JohnHake commented on CODE_OF_CONDUCT.md
> +Please make sure you read it.
Superfluous style change. Or is this affecting form or function in some way?

2020-09-10 04:18 UTC, JohnHake commented on _SUMMARY.md
> +* [Dynamic Plugins](basics/plugin_structure/dynamic_plugins.md)
Superfluous style change.

2020-09-10 04:18 UTC, JohnHake commented on appendix/glossary.md
> +: The API for [Version Control System](/reference_guide/vcs_integration_for_plugins.md) allows accessing builtin as well as adding custom implementations.
Superfluous style change.

2020-09-10 04:18 UTC, JohnHake commented on appendix/glossary.md
> +: A [Virtual File System](/basics/virtual_file_system.md) provides a unified API for working with files represented as &rarr; _Virtual File_.
Superfluous style change.

2020-09-10 04:18 UTC, JohnHake commented on appendix/plugin_repository_obsolete.md
> -
Superfluous style change.

2020-09-10 04:18 UTC, JohnHake commented on appendix/plugin_repository_obsolete.md
> +> **WARNING** **Part X - Plugin Repository** pages have moved to [JetBrains Marketplace](https://plugins.jetbrains.com/docs/marketplace/about-marketplace.html) documentation, please update your bookm
Correct changes per our style guide, but these aren't content changes, so they are superfluous to our users.

2020-09-14 00:46 UTC, JohnHake requested changes
Thanks for your patience; there are a lot of good improvements here. 
* Evaluating changes to understand if they altered the meaning of a sentence provided some unexpected puzzles.
* I tried to add some brief explanations about my comments...
  * Sometimes synonym substitutions have subtle, unintended changes to meaning.
  * Grammarly is occasionally confused by our writing and offers incorrect suggestions.
  * en-US vs en-GB styles of English
  * And of course, colloquial English.
* I _think_ I have removed all comments about systemic problems (e.g., using "we, you", proper vs. common nouns) into existing or new YT copyediting issues. If I missed a comment specifically about systemic problems, please don't consider it something you should fix for this PR. 
* I tried using the "Insert a suggestion" GitHub review feature so you would have the option to directly accept suggestions as changes in your submission.
* Please, if you don't mind, once you merge PR316 changes into `intellij-sdk-docs/master`, also perform a general maintenance merge from `master` into the `webhelp` branch. (TIA.)

2020-09-15 14:56 UTC, YannCebron commented on tutorials/framework.md
> +    retur ew FrameworkSupportInModuleProvider() {
@hsz how did this pass checks on CI?

2020-09-15 14:57 UTC, YannCebron reviewed
after handling John's comments and push, please merge back to `webhelp` branch, Thanks!

2020-09-21 14:39 UTC, hsz commented on products/clion.md
> +* [C/C++ Single File Execution](https://github.com/corochann/SingleFileExecutionPlugin)
That was some other plus that looked like a plus sign — the magic of ASCII.

2020-09-21 14:39 UTC, hsz commented on basics/ide_development_instance.md
>  * Go to the [JetBrains Runtime Site](https://confluence.jetbrains.com/display/JBR/JetBrains+Runtime) for general information and the latest build.
Yan did it by purpose: https://github.com/JetBrains/intellij-sdk-docs/commit/f5e77e1dccc1b37e9eddbc02696c9a3579c8e60f

2020-09-21 15:15 UTC, merged