Migrate gradle build scripts from groovy to kotlin
JetBrains/intellij-sdk-docs pull request #684
Opened 2022-03-23 15:11 UTC by karollewandowski

Migration done without any changes to the properties values.

Unfortunately, Git detects file deletion and addition instead of renaming.

2022-03-23 15:21 UTC, YannCebron commented
why did code_samples.yml not run in _Checks_ for this PR??

2022-03-23 15:25 UTC, YannCebron requested changes
no verification of PR on GH actions?!

2022-03-23 20:12 UTC, halirutan commented on topics/tutorials/kotlin.md
> +Gradle also supports using Kotlin in the build scripts: <path>build.gradle.kts</path>.
Remove "the" again. Plural nouns _can_ be used with a definite article but they don't need it. The original version reads better.

2022-03-23 20:12 UTC, halirutan commented on code_samples/simple_language_plugin/build.gradle.kts
> +    // This path value is machine-specific placeholder text.
... is _a_ machine-specific...

2022-03-24 08:55 UTC, YannCebron approved these changes

2022-03-24 13:54 UTC, merged